# -*- coding: utf-8 -*-
"""Copy of Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvUr4cG69P6nY6QutBOpI6SOU96naPB9

#**THRIVE**

(Testing Human Response in Variable Environments) will provide a robust Machine Learning Classifier for Detection of Physical Activity Types and Postures During Free-Living which helps in developing applications like fitness tracking, health monitoring, AI-driven rehabilitation, and wearable sensor technology.

# **Step 1:** **Import Libraries**

Start by importing the necessary libraries for data manipulation,visualization and machine learning.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, date
import seaborn as sns

"""# **Step 2: Load Data**

Here, we load the dataset using its URL. This dataset is in CSV format and can be loaded directly into a pandas DataFrame.
"""

thrive_dateset = "/content/Thrive Dataset - S006.csv"
df = pd.read_csv(thrive_dateset)

"""# Basic checks to understand the dataset"""

print(df.head)

print(df.shape)

print(df.columns)

print(df.describe())

df['label'].unique()

print('We have {} NaN or Null values in dataset'.format(df.isnull().values.sum()))

print('No of duplicates in the dataset: {}'.format(sum(df.duplicated())))

"""# **Step 3: Data Preprocessing**

Converting timestamp to a datetime format
"""

from datetime import datetime, date

# Convert 'timestamp' column to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'], infer_datetime_format=True)

# Drop timestamp column (not useful for modeling)
df = df.drop(columns=['timestamp'])

"""Creating new magnitude features (back_mag and thigh_mag)."""

# Create magnitude features
df['back_mag'] = np.sqrt(df['back_x']**2 + df['back_y']**2 + df['back_z']**2)
df['thigh_mag'] = np.sqrt(df['thigh_x']**2 + df['thigh_y']**2 + df['thigh_z']**2)

print(df.head())

"""# Handle missing values"""

df = df.dropna()  # Or df.fillna(method='ffill', inplace=True) depending on the scenario

"""# Activity Mapping"""

# Mapping labels to activity names
activity_map = {
    1: 'walking',
    2: 'running',
    3: 'shuffling',
    4: 'stairs (ascending)',
    5: 'stairs (descending)',
    6: 'standing',
    7: 'sitting',
    8: 'lying',
    13: 'cycling (sit)',
    14: 'cycling (stand)',
    130: 'cycling (sit, inactive)',
    140: 'cycling (stand, inactive)'
}

df['Activity'] = df['label'].map(activity_map)

"""# **Outlier Detection**

The Z-Score method detects outliers based on the number of standard deviations a data point is from the mean
"""

from scipy.stats import zscore

# Apply z-score to each feature (excluding the target column, like 'Activity')
df_zscore = df.copy()

# Select the features for Z-score computation
features = ['back_x', 'back_y', 'back_z', 'thigh_x', 'thigh_y', 'thigh_z', 'back_mag', 'thigh_mag']
df_zscore[features] = df_zscore[features].apply(zscore)

# Set threshold for Z-score (commonly used is 3 or -3)
threshold = 3

# Find rows where any of the features have a Z-score greater than the threshold
outliers = (df_zscore[features].abs() > threshold).any(axis=1)

# Check the number of outliers
print(f"Number of outliers detected using Z-Score: {outliers.sum()}")

# Optionally, remove the outliers
df_cleaned_zscore = df[~outliers]

# Check the shape before and after removing outliers
print(f"Shape before removing outliers: {df.shape}")
print(f"Shape after removing outliers: {df_cleaned_zscore.shape}")

# Function to detect outliers using IQR method
def detect_outliers_iqr(df, features):
    outliers = pd.DataFrame(index=df.index)

    for feature in features:
        Q1 = df[feature].quantile(0.25)
        Q3 = df[feature].quantile(0.75)
        IQR = Q3 - Q1

        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers[feature] = (df[feature] < lower_bound) | (df[feature] > upper_bound)

    return outliers

# Apply IQR method
outliers_iqr = detect_outliers_iqr(df, features)

# Count the number of outliers detected
outliers_count = outliers_iqr.any(axis=1).sum()
print(f"Number of outliers detected using IQR: {outliers_count}")

# Optionally, remove the outliers
df_cleaned_iqr = df[~outliers_iqr.any(axis=1)]

# Check the shape before and after removing outliers
print(f"Shape before removing outliers: {df.shape}")
print(f"Shape after removing outliers: {df_cleaned_iqr.shape}")

plt.figure(figsize=(12, 6))
sns.boxplot(data=df[features])
plt.xticks(rotation=45)
plt.title("Boxplot for Feature Outliers")
plt.show()
df['is_outlier'] = outliers

"""# **Step 4: Data Standardization**

Standardize your numerical features so that all features contribute equally during machine learning or visualization. This is especially important when using techniques like PCA.
"""

from sklearn.preprocessing import StandardScaler

# Select sensor features
features = ['back_x', 'back_y', 'back_z', 'thigh_x', 'thigh_y', 'thigh_z', 'back_mag', 'thigh_mag']
X = df[features].dropna()

# Standardize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# **Step 5: Visualizing the Data**

Countplot of Activities
"""

sns.set_style('whitegrid')
plt.rcParams['font.family'] = 'Dejavu Sans'
sns.set_palette("Set1", desat=0.80)

plt.figure(figsize=(16,8))
plt.title('Data Count per Activity', fontsize=20)
sns.countplot(x='Activity', data=df, order=df['Activity'].value_counts().index)
plt.xticks(rotation=45)
plt.show()

"""Back Sensor Magnitude (General View)"""

sns.set_palette("Set1", desat=0.80)
facetgrid = sns.FacetGrid(df, hue='Activity', height=6, aspect=2)

facetgrid.map(sns.kdeplot, 'back_mag', fill=False).add_legend()

plt.annotate("Stationary Activities", xy=(0.8, 5), xytext=(1.1, 10), size=14,
             va='center', ha='left',
             arrowprops=dict(arrowstyle="simple", connectionstyle="arc3,rad=0.1"))

plt.annotate("Moving Activities", xy=(1.5, 2), xytext=(1.7, 6), size=14,
             va='center', ha='left',
             arrowprops=dict(arrowstyle="simple", connectionstyle="arc3,rad=0.1"))

plt.tight_layout()
plt.show()

"""KDE Plots for Magnitudes"""

plt.figure(figsize=(12,8))

# Static Activities (closer view) - Back Magnitude
plt.subplot(2,2,1)
plt.title("Static Activities (Back Magnitude)")
sns.kdeplot(df[df["Activity"]=="sitting"]['back_mag'], label='Sitting', fill=True)
sns.kdeplot(df[df["Activity"]=="standing"]['back_mag'], label='Standing', fill=True)
sns.kdeplot(df[df["Activity"]=="lying"]['back_mag'], label='Lying', fill=True)
plt.axis([0, 3, 0, 35])

# Dynamic Activities (closer view) - Back Magnitude
plt.subplot(2,2,2)
plt.title("Dynamic Activities (Back Magnitude)")
sns.kdeplot(df[df["Activity"]=="walking"]['back_mag'], label='Walking', fill=True)
sns.kdeplot(df[df["Activity"]=="cycling (sit)"]['back_mag'], label='Cycling (sit)', fill=True)
sns.kdeplot(df[df["Activity"]=="shuffling"]['back_mag'], label='Shuffling', fill=True)
plt.axis([0, 3, 0, 35])

# Static Activities (closer view) - Thigh Magnitude
plt.subplot(2,2,3)
plt.title("Static Activities (Thigh Magnitude)")
sns.kdeplot(df[df["Activity"]=="sitting"]['thigh_mag'], label='Sitting', fill=True)
sns.kdeplot(df[df["Activity"]=="standing"]['thigh_mag'], label='Standing', fill=True)
sns.kdeplot(df[df["Activity"]=="lying"]['thigh_mag'], label='Lying', fill=True)
plt.axis([0, 3, 0, 35])

# Dynamic Activities (closer view) - Thigh Magnitude
plt.subplot(2,2,4)
plt.title("Dynamic Activities (Thigh Magnitude)")
sns.kdeplot(df[df["Activity"]=="walking"]['thigh_mag'], label='Walking', fill=True)
sns.kdeplot(df[df["Activity"]=="cycling (sit)"]['thigh_mag'], label='Cycling (sit)', fill=True)
sns.kdeplot(df[df["Activity"]=="shuffling"]['thigh_mag'], label='Shuffling', fill=True)
plt.axis([0, 3, 0, 35])

plt.tight_layout()
plt.show()



""" **Histogram**"""

df[['back_x', 'back_y', 'back_z', 'thigh_x', 'thigh_y', 'thigh_z']].hist(bins=20, figsize=(10, 8))
plt.tight_layout()
plt.show()

""" **Box Plot**"""

sns.boxplot(data=df[['back_x', 'back_y', 'back_z', 'thigh_x', 'thigh_y', 'thigh_z']])
plt.xticks(rotation=45)
plt.show()

"""
 **Correlation Matrix**"""

correlation_matrix = df[['back_x', 'back_y', 'back_z', 'thigh_x', 'thigh_y', 'thigh_z', 'back_mag', 'thigh_mag']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0)
plt.show()

"""# **Step 6: Dimensionality Reduction**

Quantitative PCA
"""

from sklearn.decomposition import PCA
pca = PCA(n_components=3)
X_pca = pca.fit_transform(X_scaled)

# Explained variance
print("Explained Variance Ratio:", pca.explained_variance_ratio_)
print("Singular Values:", pca.singular_values_)

# Add PCs to the original dataframe
df_pca = df.loc[X.index].copy()
df_pca['PC1'] = X_pca[:, 0]
df_pca['PC2'] = X_pca[:, 1]
df_pca['PC3'] = X_pca[:, 2]

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_pca, x='PC1', y='PC2', hue='Activity', alpha=0.6, palette='tab10')
plt.title('PCA Projection (PC1 vs PC2)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(loc='best', bbox_to_anchor=(1, 1))
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 4))
sns.barplot(x=[f'PC{i+1}' for i in range(len(pca.explained_variance_ratio_))],
            y=pca.explained_variance_ratio_)
plt.ylabel("Explained Variance Ratio")
plt.title("PCA - Explained Variance per Component")
plt.show()

"""**Confusion Matrix**"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Assuming you already have y_test and y_pred
# y_test = ... (your actual test labels)
# y_pred = ... (your predicted labels from saved model)

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues')

plt.title("Confusion Matrix")
plt.show()

"""# **Step 7: Model Building**

Model 1: Logistic Regression

Logistic Regression is a statistical model used for binary classification tasks, though it can be extended to multiclass classification. It predicts the probability of a binary outcome based on one or more predictor variables by applying a logistic function. The output is a value between 0 and 1, which can be interpreted as a probability.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# Prepare data
X = df[features]  # Features
y = df['Activity']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Initialize and train the model
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

# Predict and evaluate
y_pred = logreg.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Logistic Regression Accuracy: {accuracy * 100:.2f}%")
print(classification_report(y_test, y_pred))

"""Model 2. Support Vector Machine (SVM)

Support Vector Machines (SVM) are supervised learning models used for classification and regression tasks. They work by finding a hyperplane that best separates data points of different classes in a high-dimensional space.
"""

from sklearn.svm import SVC

# Initialize and train the model
svm = SVC(kernel='rbf', random_state=42)
svm.fit(X_train, y_train)

# Predict and evaluate
y_pred_svm = svm.predict(X_test)
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {accuracy_svm * 100:.2f}%")
print(classification_report(y_test, y_pred_svm))

"""Model 3. Gradient Boosting Classifier

Gradient Boosting is another ensemble learning technique that builds strong models by combining the predictions of multiple weak learners (typically decision trees). It works by fitting a new model to the residual errors (differences between predicted and actual values) of the previous models.
"""

from sklearn.ensemble import GradientBoostingClassifier

# Initialize and train the model
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
gb.fit(X_train, y_train)

# Predict and evaluate
y_pred_gb = gb.predict(X_test)
accuracy_gb = accuracy_score(y_test, y_pred_gb)
print(f"Gradient Boosting Accuracy: {accuracy_gb * 100:.2f}%")
print(classification_report(y_test, y_pred_gb))

"""Model 4. Random Forest Classifier

Random Forest is an ensemble learning method that creates a 'forest' of decision trees, usually trained with the "bagging" technique. Each tree in the forest is trained on a random subset of the data and makes a classification decision.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Initialize and train the model
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Predict and evaluate
y_pred_rf = rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf * 100:.2f}%")
print(classification_report(y_test, y_pred_rf))

"""# **Step 8: Model Comparison**

To compare these models, you can evaluate their accuracy and other metrics like precision, recall, and F1 score. Here’s how you can print a comparison of their performances:






"""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Models
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'SVM': SVC(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier()
}

# Dictionary to store results
results = {}

# Train, predict, evaluate
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    results[name] = {
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, average='weighted'),
        'Recall': recall_score(y_test, y_pred, average='weighted'),
        'F1-Score': f1_score(y_test, y_pred, average='weighted')
    }

# Display results
import pandas as pd
results_df = pd.DataFrame(results).T
print(results_df)

"""# **Step 9:** **Hyperparameter Tuning**

Logistic Regression:

After hyperparameter tuning, the accuracy slightly improved from 86.58% to 86.76%, showing a marginal gain of about 0.18%, fine-tuning the regularization strength improved stability.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Define parameter grid for Logistic Regression
param_logreg = {
    'C': [0.01, 0.1, 1, 10],         # Regularization strength
    'penalty': ['l2'],               # L2 regularization (L1 needs 'liblinear' solver)
    'solver': ['lbfgs']              # Solver that works with 'l2'
}

# Set up GridSearchCV
grid_logreg = GridSearchCV(
    estimator=LogisticRegression(max_iter=1000),
    param_grid=param_logreg,
    cv=5,                            # 5-fold cross-validation
    scoring='accuracy',
    n_jobs=-1               # Evaluation metric
)

# Fit to training data
grid_logreg.fit(X_train, y_train)

# Print best parameters and score
print("Best Parameters for Logistic Regression:", grid_logreg.best_params_)
print("Best Cross-Validated Accuracy:", grid_logreg.best_score_)

"""Support Vector Machine:

The accuracy improved from 90.69% to 91.02%, giving a boost of around 0.33%, indicating that optimal kernel and C value enhanced its classification margin.
"""

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# Smaller grid for faster execution
param_grid = {
    'C': [1, 10],                 # Fewer values
    'gamma': ['scale', 0.1],     # Keep scale and one float
    'kernel': ['rbf']            # Just RBF for non-linearity
}

# GridSearchCV setup with fewer folds
grid_search = GridSearchCV(
    estimator=SVC(),
    param_grid=param_grid,
    cv=2,                         # 2-fold CV to save time
    scoring='accuracy',
    n_jobs=-1
)

# Fit the model
grid_search.fit(X_train, y_train)

# Output best results
print("Best Parameters:", grid_search.best_params_)
print("Best Cross-Validated Accuracy:", grid_search.best_score_)

"""Support Vector Machine (Test-case):

Since only 200,000 samples were used for hyperparameter tuning, the SVM model had limited data to capture complex patterns. Additionally, the parameter grid was small with only C and gamma tuned, which restricted the model's ability to find more optimal settings, resulting in slightly lower accuracy.
"""

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# Step 1: Sample the dataset to speed up
df_sample = df.sample(n=200000, random_state=42)  # You can reduce to 3000 if still slow
X_sample = df_sample[features]
y_sample = df_sample['Activity']

# Step 2: Define a small grid
param_grid = {
    'C': [1, 10],               # Regularization strength
    'gamma': ['scale'],         # Kernel coefficient
    'kernel': ['rbf']           # RBF kernel only
}

# Step 3: Set up GridSearchCV with fewer combinations
grid_search = GridSearchCV(
    estimator=SVC(),
    param_grid=param_grid,
    cv=3,                       # 3-fold cross-validation
    scoring='accuracy',
    n_jobs=-1                   # Use all CPU cores
)

# Step 4: Fit on the small sample
grid_search.fit(X_sample, y_sample)

# Step 5: Print best parameters and score
print("Best SVM Parameters (GridSearchCV):", grid_search.best_params_)
print("Best Cross-Validated Accuracy:", grid_search.best_score_)

"""Random Forest Classifier (Test-case):

 A limited hyperparameter grid with fewer parameter combinations was used for tuning Random Forest. As only n_estimators and max_depth were tuned, the model explored fewer configurations, resulting in relatively lower accuracy compared to wider grid searches.


"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd

# Sample just 5000 rows for faster tuning
df_sample = df.sample(n=352301, random_state=42)
X_sample = df_sample[features]
y_sample = df_sample['Activity']

# Define a small hyperparameter grid
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
}

# Grid search with fast setup
grid_rf = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=3,
    scoring='accuracy',
    n_jobs=-1  # Use all cores
)

# Fit on sampled data
grid_rf.fit(X_sample, y_sample)

# Output best parameters and score
print("Best Random Forest Params:", grid_rf.best_params_)
print("Best Accuracy:", grid_rf.best_score_)

"""Gradient Boosting Classifier (Test-case):

In this code, hyperparameter tuning was performed on a randomly sampled subset of 200,000 instances to reduce computation time. Since the model was trained on fewer instances, it had access to less information, leading to slightly lower accuracy. Using the full dataset generally provides better learning and improved performance.
"""

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

# Randomly sample 5000 rows for speed (safe for large datasets)
indices = np.random.choice(len(X_train), 200000, replace=False)
X_small = X_train[indices]
y_small = y_train.iloc[indices]  # Use .iloc to match index positions

# Define a small parameter grid
param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.2],
    'max_depth': [3, 4]
}

# Set up GridSearchCV
grid_search_gb = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    param_grid=param_grid,
    cv=2,  # 3-fold for speed
    scoring='accuracy',
    n_jobs=-1  # Use all CPU cores
)

# Fit the model
grid_search_gb.fit(X_small, y_small)

# Output the results
print("Best Parameters:", grid_search_gb.best_params_)
print("Best Cross-Validated Accuracy:", grid_search_gb.best_score_)

"""Random Forest Classifier

The model showed a significant jump from 92.89% to nearly 100% accuracy (99.99%) after tuning, due to better depth control and optimal tree configuration.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd

# If not already done: load your full DataFrame
# df = pd.read_csv('your_dataset.csv')  # Uncomment and modify if needed

# Define the features and target
features = [col for col in df.columns if col != 'Activity']
target = 'Activity'

# Sample all 352301 rows (as requested) but reassign properly
df_sample = df.sample(n=352301, random_state=42)
X_sample = df_sample[features]
y_sample = df_sample[target]

# Define a smart parameter grid
param_grid = {
    'n_estimators': [100, 150],
    'max_depth': [10, 20],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# Setup GridSearchCV
grid_rf = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=3,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

# Fit the model
grid_rf.fit(X_sample, y_sample)

# Output best result
print("Best Random Forest Params:", grid_rf.best_params_)
print("Best Accuracy:", grid_rf.best_score_)

"""Gradient Boosting Classifier (Test-case):

Hyperparameter tuning was performed on the full dataset (X and y) including both training and unseen data, which may lead to lower accuracy due to potential data leakage or mixed data distributions. Ideally, tuning should be done only on the training set to get more reliable results.
"""

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd

# Use your full dataset
# df = pd.read_csv(...)  # already loaded
# features = [...]       # already defined list of column names
# target column is 'Activity'

X = df[features].values
y = df['Activity'].values  # ✅ Replaced target with 'Activity'

# Define a small but effective parameter grid
param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.2],
    'max_depth': [3, 4]
}

# GridSearchCV setup
grid_search_gb = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    param_grid=param_grid,
    cv=2,
    scoring='accuracy',
    n_jobs=-1
)

# Fit model on entire dataset
grid_search_gb.fit(X, y)

# Output results
print("Best Parameters:", grid_search_gb.best_params_)
print("Best Cross-Validated Accuracy:", grid_search_gb.best_score_)

"""Gradient Boosting Classifier:

The accuracy increased from 90.78% to 91.15%, a gain of roughly 0.37%, as fine-tuning learning rate and tree depth allowed better convergence.

Hyperparameter tuning was correctly performed only on the training set (X_train and y_train), which helps prevent data leakage and ensures the model generalizes better. As a result, the accuracy is higher and more reliable when evaluated on unseen test data.
"""

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

# Define the full dataset (no sampling needed)
X_small = X_train  # Using all 352301 instances
y_small = y_train

# Define a small parameter grid
param_grid = {
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.2],
    'max_depth': [3, 4]
}

# Set up GridSearchCV
grid_search_gb = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    param_grid=param_grid,
    cv=2,             # Keep low for speed
    scoring='accuracy',
    n_jobs=-1         # Use all CPU cores
)

# Fit the model
grid_search_gb.fit(X_small, y_small)

# Output the results
print("Best Parameters:", grid_search_gb.best_params_)
print("Best Cross-Validated Accuracy:", grid_search_gb.best_score_)

"""# **Step 7: Deployment**"""

from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import pickle

# Define the 6 required features and target
features = ['back_x', 'back_y', 'back_z', 'thigh_x', 'thigh_y', 'thigh_z']
target = 'Activity'

# Sample full data with only those features
df_sample = df.sample(n=352301, random_state=42)
X_sample = df_sample[features]
y_sample = df_sample[target]

# Train Random Forest with best-known params
best_rf = RandomForestClassifier(
    n_estimators=150,
    max_depth=20,
    min_samples_split=2,
    max_features='sqrt',
    random_state=42
)

# Fit the model
best_rf.fit(X_sample, y_sample)

# Save the model using pickle
with open('best_rf_6_features.pkl', 'wb') as file:
    pickle.dump(best_rf, file)

print("Model trained with 6 features and saved as best_rf_6_features.pkl")

from google.colab import files
files.download('best_rf_6_features.pkl')

<!doctype html>
<html lang="en">

<head>
  <title>THRIVE | Real-Time Movement Prediction</title>
  <style>
    :root {
      --primary: #1ed2a5;
      --hover: #2f3a3c;
      --light: #fafff2;
      --text: #2f3a3c;
      --accent: #fcff47;
    }

    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background: var(--light);
      color: var(--text);
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: flex-start;
      min-height: 100vh;
      margin: 0;
      padding: 40px;
      box-sizing: border-box;
    }

    header {
      text-align: center;
      margin-bottom: 30px;
    }

    header h1 {
      margin: 0;
      font-size: 3em;
      color: var(--primary);
    }

    header p {
      font-size: 1.1em;
      color: #6a4e3e;
      max-width: 600px;
      margin: 10px auto 0;
    }

    /* ---- New: Container for side-by-side layout ---- */
    .main-container {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: 40px;
      width: 100%;
      max-width: 1250px;
      margin-top: 30px;
    }

    .features {
      flex: 1;
      min-width: 300px;
      max-width: 700px;
      text-align: left;
    }

    .features h3 {
      color: var(--text);
      margin-bottom: 15px;
    }

    .features ul {
      list-style-type: none;
      padding: 0;
    }

    .features li {
      background-color: #fff;
      padding: 12px 20px;
      margin: 10px 0;
      border-left: 5px solid var(--primary);
      border-radius: 4px;
      text-align: left;
      box-shadow: 0 1px 5px rgba(210, 105, 30, 0.2);
    }

    /* ---- Form panel in side-by-side layout ---- */
    .form-panel {
      flex: 1;
      min-width: 300px;
      max-width: 400px;
    }

    h2 {
      margin-bottom: 20px;
      color: var(--text);
    }

    form {
      background: #fff;
      padding: 30px 20px;
      border-radius: 20px;
      box-shadow: 0 2px 10px rgba(210, 105, 30, 0.2);
      width: 100%;
      box-sizing: border-box;
    }

    label {
      font-weight: 600;
      display: block;
      margin-top: 15px;
      color: var(--text);
    }

    input[type="text"] {
      width: 100%;
      padding: 10px;
      margin-top: 5px;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
    }

    input[type="submit"] {
      margin-top: 20px;
      width: 100%;
      padding: 12px;
      background-color: var(--primary);
      color: white;
      border: none;
      border-radius: 5px;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
      background-color: var(--hover);
    }

    /* Modal Styling */
    .modal {
      display: none;
      position: fixed;
      z-index: 1000;
      left: 0;
      top: 0;
      width: 100%;
      height: 100%;
      overflow: auto;
      background-color: rgba(0, 0, 0, 0.5);
    }

    .modal-content {
      background-color: #fff;
      margin: 15% auto;
      padding: 20px 30px;
      border: 1px solid var(--primary);
      width: 80%;
      max-width: 400px;
      border-radius: 8px;
      box-shadow: 0 5px 15px rgba(210, 105, 30, 0.3);
      text-align: center;
      position: relative;
    }

    .modal h3 {
      color: var(--primary);
      margin-bottom: 10px;
    }

    .close {
      color: #999;
      position: absolute;
      top: 10px;
      right: 15px;
      font-size: 24px;
      font-weight: bold;
      cursor: pointer;
    }

    .close:hover,
    .close:focus {
      color: #000;
    }

    form fieldset {
      border: none;
      margin: 20px 0;
      padding: 0;
    }

    form legend {
      font-weight: bold;
      margin-bottom: 9px;
      color: var(--primary);
    }

    .input-row {
      display: flex;
      gap: 5px;
      align-items: center;
      flex-wrap: wrap;
    }

    .input-row label {
      margin-top: 0;
    }

    .input-row input[type="text"] {
      width: 80px;
      padding: 8px;
    }


    /* ---- Responsive Layout ---- */
    @media (max-width: 768px) {
      .main-container {
        flex-direction: column;
        align-items: stretch;
      }
    }
  </style>

</head>

<body>
  <header>
    <h1>THRIVE</h1>
    <p>Testing Human Response in Variable Environments</p>
    <p>
      Thrive provides a robust Machine Learning Classifier for Detection of Physical Activity Types and Postures During
      Free-Living. Applications include fitness tracking, health monitoring, AI-driven rehabilitation, and wearable
      sensor technology.
    </p>
  </header>
  <div class="main-container">
    <section class="features">
      <h3>What is Thrive?</h3>
      <ul>
        <li><strong>Thrive</strong> interprets real-time motion data from wearable sensors.</li>
        <li>Helps detect posture, activity type, or risk patterns from accelerometer input.</li>
        <li>Ideal for healthcare, physiotherapy, sports science, and workplace safety.</li>
      </ul>

      <h3>Core Features</h3>
      <ul>
        <li>Live sensor input: back and thigh accelerometers.</li>
        <li>ML model delivers instant activity predictions.</li>
        <li>Clean, intuitive UI with visual feedback.</li>
      </ul>
    </section>

    <div class="form-panel">
      <h2>Try It Now</h2>
      <form action="/predict" method="post">
        <fieldset>
          <legend>Thigh: Enter Coordinates</legend>
          <div class="input-row">
            <label for="thigh_x">X:</label>
            <input type="text" name="thigh_x" required>

            <label for="thigh_y">Y:</label>
            <input type="text" name="thigh_y" required>

            <label for="thigh_z">Z:</label>
            <input type="text" name="thigh_z" required>
          </div>
        </fieldset>

        <fieldset>
          <legend>Back: Enter Coordinates</legend>
          <div class="input-row">
            <label for="back_x">X:</label>
            <input type="text" name="back_x" required>

            <label for="back_y">Y:</label>
            <input type="text" name="back_y" required>

            <label for="back_z">Z:</label>
            <input type="text" name="back_z" required>
          </div>
        </fieldset>

        <input type="submit" value="Predict">
      </form>

    </div>
  </div>

  {% if prediction_text %}
  <div id="predictionModal" class="modal">
    <div class="modal-content">
      <span class="close" onclick="document.getElementById('predictionModal').style.display='none'">&times;</span>
      <h3>Prediction Result</h3>
      <p>{{ prediction_text }}</p>
    </div>
  </div>
  <script>
    window.onload = function () {
      document.getElementById('predictionModal').style.display = 'block';
    };
  </script>
  {% endif %}
</body>

</html>